owner: tattle-made
repo: status-page

sites:
  - name: Kosh
    url: https://kosh-server.tattle.co.in/
    expectedStatusCodes:
      - 401
  - name: Annotator UI
    url: http://ogbv-annotator.tattle.co.in/
  - name: ElasticSearch
    url: http://13.234.125.86:9200

status-website:
  baseUrl: /status-page
  logoUrl: https://blog.tattle.co.in/content/images/2020/05/xmonogram.png.pagespeed.ic.2hCvSeijLj.png
  name: Tattle
  introTitle: "Monitor Status of Tattle Services here."
  introMessage: We provide near realtime status updates on our various services. Each outage has an associated github issue where you can track its progress or help fix it.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/tattle-made/status-page
  theme: light

assignees:
  - dennyabrain
  - d80ep08th 
